### ISSUE TITLE
Global styling

### ISSUE THREAD

**Issue by cziegeler** [hlxsites/sazerac-wheatleyvodka#38]
Global styling of pages, like padding/margin on desktop etc.

**Comment by mujtabach2** [comment]
You can define global styles for elements in CSS. You can use media queries for creating responsive designs that adapt to different screen sizes.

```css
/* Base styles for all screen sizes */
body {
  font-size: 16px;
}

/* Styles for screens with a minimum width of 1024px (desktop) */
@media (min-width: 1024px) {
  body {
    font-size: 18px;
    padding: 20px;
  }
}
```
[Media Queries Documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries)
